derives some useful traits
SfietKonstantin/pretend pull request #28
Opened 2021-06-23 12:51 UTC by orzogc

2021-06-23 17:17 UTC, SfietKonstantin requested changes
You might also want to implement Clone, Debug for pretend-awc.

2021-06-23 17:17 UTC, SfietKonstantin commented on pretend/src/lib.rs
> +#[derive(Clone, Debug, Eq, PartialEq, Hash)]
I'm not sure that you want to compare a client, so Eq, PartialEq and Hash might not make sense too much ...

2021-06-23 17:17 UTC, SfietKonstantin commented on pretend/src/resolver.rs
> +#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
Same as for Pretend, this is a rather technical struct, so Clone, Debug make sense, but not really Eq, Ord and Hash.

2021-06-24 02:28 UTC, orzogc commented
> You might also want to implement Clone, Debug for pretend-awc.
> 
> Otherwise, thanks for these useful contributions :)

[awc::Client](https://docs.rs/awc/2.0.3/awc/struct.Client.html) doesn't implement the `Debug` trait.

2021-06-24 06:24 UTC, SfietKonstantin commented
Thanks for this contribution !
I will merge (and have a look at awc)

2021-06-24 06:25 UTC, merged